nome = input("Digite o nome do cliente: ")
data_vencimento = input("Digite o dia de vencimento: ")
mes_vencimento = input("Digite o mês de vencimento: ")
fatura = input("Digite o valor da fatura: ")
print("Olá,",nome)
print("A sua fatura com vencimento em",data_vencimento,"de",mes_vencimento,"no valor de R$",fatura,"está fechada.")